### PR TITLE
chore: dredd was move into separate repository https://github.com/api…

### PR DESCRIPTION
**Pull request by abtris**
…aryio/dredd-docker

### CODE REVIEW

**Comment by honzajavorek** [comment]
If you want to link repo, please link https://github.com/apiaryio/dredd-docker. If you want to link docs, please link https://dredd.org/en/latest/installation.html#docker. I'll be updating the https://github.com/apiaryio/dredd-docker README to link to the docs not to duplicate content.

**Comment by abtris** [comment]
I don't need mention dredd. This repo isn't related to them, this just record in commits.

**Comment by abtris** [comment]
But will be useful change link and readme in dockerhub - https://hub.docker.com/r/apiaryio/dredd/

**Comment by honzajavorek** [comment]
@abtris How do I change the DockerHub description? I don't seem to have an account there 😬

**Comment by abtris** [comment]
I update readme, but can't change source repository. I can add you if you create account.

**Comment by honzajavorek** [comment]
> can't change source repository

That's a problem, isn't it? People will be landing to this repo instead of dredd-docker, without any clue where to find the source, because we didn't update the README 😐

**Comment by abtris** [comment]
ok, I will add into readme.

**Comment by honzajavorek** [comment]
Thanks, I updated the DockerHub description. It looks like there's no way to change the source repo 🤦‍♂️  https://github.com/docker/hub-feedback/issues/313

**Pull request merged**
