### PR TITLE
Add dredd to alpine (size reduced from 700MB -> 285MB)

### PR DESCRIPTION
**Pull request by abtris**
- Reduce size of image.

### CODE REVIEW

**Comment by abtris** [comment]
@honzajavorek here is dredd updated version, just 285MB ;-)

**Comment by honzajavorek** [comment]
Great!

It seems like `dredd` isn't executable within the machine anymore (full path needs to be provided). I think that could make some testing (e.g. the Cucumber one) problematic (if we're about to run Dredd tests on top of this image).

**Comment by abtris** [comment]
This isn't intension using dredd tool in docker container itself. For testing you can use another image where you add sources into container.

**Comment by kylef** [comment]
Not sure that is the case, this PR seems to have actually broken the polls-api script you referenced. See https://github.com/apiaryio/polls-api/pull/41

**Comment by abtris** [comment]
I think add `node_modules/.bin` to PATH to fix this. Good point.

**Pull request merged**
